name: PR workflow, basic

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
    branches:
      - main

jobs:

  a_pr_job:
    name: the first job in PR workflow
    runs-on: ubuntu-latest
    steps:
      - name: show something
        run: echo "in a step of PR job"

  fails_a_build:
    name: fail a WIP pr build
    runs-on: ubuntu-latest
    needs: a_pr_job
    env:
      IS_WIP_PR: ${{ contains(github.event.pull_request.labels.*.name, 'wip') }}
    steps:
      - name: fail job
        run: |
          echo $IS_WIP_PR
          if [ $IS_WIP_PR ]
          then
            echo 'it is WIP'
          fi
          [ $IS_WIP_PR = 'true' ] && exit 1


